rm -f sampleThesis.aux
rm -f sampleThesis.bbl
rm -f sampleThesis.dvi
rm -f sampleThesis.fdb_latexmk
rm -f sampleThesis.fls
rm -f sampleThesis.lof
rm -f sampleThesis.log
rm -f sampleThesis.lot
rm -f sampleThesis.toc
rm -f sampleThesis.blg
